id: IF1C6D66B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-16T11:40:58+00:00'
last_modified: '2022-06-10T04:58:15.220916+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W17788
  title: མན་ངག་རིན་ཆེན་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A606:
      image_group_id: I4797
      title: ''
      total_pages: 954
      order: 1
      base_file: A606.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
